import test from 'node:test';
import assert from 'node:assert/strict';
import { deflateRawSync } from 'node:zlib';
import { readFile } from 'node:fs/promises';
import { DEFAULTS, LIMITS, optionsFrom, validateFile, dateFromName, sortEntries, transcriptText, timeLabel, checkAbort } from '../web/core.js';
import { crc32, openInputs } from '../web/zip.js';
import { recognitionOptions } from '../web/engine.js';
import { filenameFor, wrapText } from '../web/export.js';
import { MODELS, TRANSFORMERS_URL } from '../web/runtime-config.js';
export function zipFixture(entries, { descriptor = false } = {}) {
  const locals = [], centrals = []; let offset = 0;
  for (const entry of entries) {
    const name = Buffer.from(entry.name), data = Buffer.from(entry.text ?? 'áudio de teste'), method = entry.method ?? 8;
    const compressed = method === 8 ? deflateRawSync(data) : data;
    const crc = entry.crc ?? crc32(data), flags = entry.flags ?? (0x800 | (descriptor ? 8 : 0));
    const size = entry.size ?? data.length;
    const local = Buffer.alloc(30); local.writeUInt32LE(0x04034b50); local.writeUInt16LE(20, 4); local.writeUInt16LE(flags, 6); local.writeUInt16LE(method, 8);
    if (!descriptor) { local.writeUInt32LE(crc, 14); local.writeUInt32LE(compressed.length, 18); local.writeUInt32LE(size, 22); }
    local.writeUInt16LE(name.length, 26);
    const central = Buffer.alloc(46); central.writeUInt32LE(0x02014b50); central.writeUInt16LE(0x314, 4); central.writeUInt16LE(20, 6); central.writeUInt16LE(flags, 8); central.writeUInt16LE(method, 10);
    central.writeUInt32LE(crc, 16); central.writeUInt32LE(compressed.length, 20); central.writeUInt32LE(size, 24); central.writeUInt16LE(name.length, 28);
    central.writeUInt32LE(entry.attributes ?? 0, 38); central.writeUInt32LE(offset, 42);
    const extra = descriptor ? Buffer.alloc(16) : Buffer.alloc(0);
    if (descriptor) { extra.writeUInt32LE(0x08074b50); extra.writeUInt32LE(crc, 4); extra.writeUInt32LE(compressed.length, 8); extra.writeUInt32LE(size, 12); }
    locals.push(local, name, compressed, extra); centrals.push(central, name); offset += local.length + name.length + compressed.length + extra.length;
  }
  const directory = Buffer.concat(centrals), end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50); end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10); end.writeUInt32LE(directory.length, 12); end.writeUInt32LE(offset, 16);
  return new File([Buffer.concat([...locals, directory, end])], 'audios.zip');
}
const run = (name, fn) => test(name, fn);
run('defaults reject arbitrary settings', () => assert.deepEqual(optionsFrom({ model: 'https://attacker', output: 'html', language: 'fake' }), DEFAULTS));
run('null preferences are safe', () => assert.deepEqual(optionsFrom(null), DEFAULTS));
run('checkbox values must be booleans', () => assert.equal(optionsFrom({ organized: 'false' }).organized, true));
run('valid settings are preserved', () => assert.equal(optionsFrom({ model: 'tiny', organized: false }).organized, false));
run('reject empty files', () => assert.throws(() => validateFile(new File([], 'voice.mp3')), /vazio/));
run('reject unsupported extension', () => assert.throws(() => validateFile(new File(['x'], 'malware.exe')), /compatível/));
run('reject oversized audio', () => assert.throws(() => validateFile({ name: 'x.wav', size: LIMITS.audio + 1 }), /Limite/));
run('reject oversized archive', () => assert.throws(() => validateFile({ name: 'x.zip', size: LIMITS.upload + 1 }), /Limite/));
run('date and time recognized from filename', () => assert.equal(dateFromName('AUDIO-2026-10-05-14-12-31.opus').label, '05/10/2026 às 14:12:31'));
run('WhatsApp date never invents a time', () => assert.equal(dateFromName('PTT-20261005-WA0001.opus').label, '05/10/2026'));
run('invalid calendar date rejected', () => assert.equal(dateFromName('audio-20260231.opus'), null));
run('invalid hour rejected', () => assert.equal(dateFromName('audio-2026-10-05-25-10-10.opus'), null));
run('missing recording date not fabricated', () => assert.equal(dateFromName('meeting.mp3'), null));
run('natural sort is 1,2,10', () => assert.deepEqual(sortEntries(['10','2','1'].map((n,index)=>({ name:n+'.mp3',index })), 'name').map(x=>x.name), ['1.mp3','2.mp3','10.mp3']));
run('dated audio first, undated last', () => assert.deepEqual(sortEntries(['unknown.mp3','AUDIO-20261006.opus','AUDIO-20261005.opus'].map((name,index)=>({name,index})), 'date').map(x=>x.index), [2,1,0]));
run('original archive order maintained', () => assert.deepEqual(sortEntries([{name:'a',index:1},{name:'z',index:0}], 'archive').map(x=>x.name), ['z','a']));
run('timestamps handle unknown end', () => { assert.equal(timeLabel(null), '--:--'); assert.equal(timeLabel(65), '01:05'); });
run('speech is transcribed, not translated', () => { const o = recognitionOptions('pt'); assert.equal(o.task, 'transcribe'); assert.equal(o.language, 'portuguese'); });
run('auto language omits forced language', () => assert.equal(Object.hasOwn(recognitionOptions('auto'), 'language'), false));
run('long speech uses overlapping 30 second chunks', () => { const o=recognitionOptions('pt'); assert.equal(o.chunk_length_s, 30); assert.equal(o.stride_length_s, 5); assert.equal(o.return_timestamps, true); });
run('all offered models are multilingual', () => assert.ok(Object.values(MODELS).every(x=>!x.endsWith('.en'))));
run('runtime is bundled with ONNX, not external-bare-import web build', () => assert.ok(TRANSFORMERS_URL.endsWith('/dist/transformers.min.js')));
run('abort is explicit', () => { const c=new AbortController(); c.abort(); assert.throws(()=>checkAbort(c.signal), {name:'AbortError'}); });
run('CRC32 known vector', () => assert.equal(crc32(Buffer.from('123456789')), 0xcbf43926));
run('single audio does not load any ZIP library', async () => { const file=new File(['audio'],'one.mp3'); const x=await openInputs(file); assert.equal(await x.entries[0].read(), file); });
run('deflate ZIP audio is actually decompressed and checked', async () => { const x=await openInputs(zipFixture([{name:'voz.opus',text:'conteúdo real da entrada'}])); assert.equal(await (await x.entries[0].read()).text(),'conteúdo real da entrada'); });
run('stored ZIP audio supported', async () => { const x=await openInputs(zipFixture([{name:'voz.wav',text:'wav',method:0}])); assert.equal(await (await x.entries[0].read()).text(),'wav'); });
run('data-descriptor ZIP supported', async () => { const x=await openInputs(zipFixture([{name:'voz.ogg',text:'descriptor'}],{descriptor:true})); assert.equal(await (await x.entries[0].read()).text(),'descriptor'); });
run('multiple audios sorted; unrelated files explicitly ignored', async () => { const x=await openInputs(zipFixture([{name:'10.mp3'},{name:'_chat.txt'},{name:'2.mp3'}]),'name'); assert.deepEqual(x.entries.map(x=>x.name),['2.mp3','10.mp3']); assert.equal(x.warnings.length,1); });
run('ZIP path traversal rejected', async () => assert.rejects(()=>openInputs(zipFixture([{name:'../voice.mp3'}])),/inseguro/));
run('absolute ZIP paths rejected', async () => assert.rejects(()=>openInputs(zipFixture([{name:'/voice.mp3'}])),/inseguro/));
run('Windows path traversal rejected', async () => assert.rejects(()=>openInputs(zipFixture([{name:'C:\\voice.mp3'}])),/inseguro/));
run('ZIP encryption rejected', async () => assert.rejects(()=>openInputs(zipFixture([{name:'voice.mp3',flags:1}])),/senha/));
run('ZIP symlinks rejected', async () => assert.rejects(()=>openInputs(zipFixture([{name:'voice.mp3',attributes:0xa1ff0000}])),/simbólicos/));
run('ZIP duplicate audio names rejected', async () => assert.rejects(()=>openInputs(zipFixture([{name:'voice.mp3'},{name:'voice.mp3'}])),/duplicados/));
run('ZIP unsupported compression rejected', async () => assert.rejects(()=>openInputs(zipFixture([{name:'voice.mp3',method:99}])),/Compressão/));
run('ZIP decompressed limit enforced before inflation', async () => assert.rejects(()=>openInputs(zipFixture([{name:'voice.mp3',size:LIMITS.expanded+1}])),/limite|compressão/));
run('ZIP mismatched actual inflated size rejected', async () => { const x=await openInputs(zipFixture([{name:'voice.mp3',text:'123456',size:2}])); await assert.rejects(()=>x.entries[0].read(),/Tamanho/); });
run('ZIP corrupt CRC rejected', async () => { const x=await openInputs(zipFixture([{name:'voice.mp3',crc:0}])); await assert.rejects(()=>x.entries[0].read(),/CRC/); });
run('ZIP without audio rejected', async () => assert.rejects(()=>openInputs(zipFixture([{name:'nested.zip'},{name:'_chat.txt'}])),/Nenhum áudio/));
run('ZIP extraction respects cancellation', async () => { const c=new AbortController(); const x=await openInputs(zipFixture([{name:'voice.mp3'}]),'name',c.signal); c.abort(); await assert.rejects(()=>x.entries[0].read(),{name:'AbortError'}); });
run('truncated ZIP rejected', async () => assert.rejects(()=>openInputs(new File(['PK'],'broken.zip')),/ler este ZIP/));
run('ZIP max audio count enforced', async () => assert.rejects(()=>openInputs(zipFixture(Array.from({length:101},(_,i)=>({name:i+'.mp3'})))),/100 áudios/));
const result = { items: [{name:'one.mp3',text:'Olá, Henrique.',chunks:[{text:'Olá, Henrique.',timestamp:[0,null]}]},{name:'two.mp3',error:'Arquivo inválido.'}], cancelled:false };
run('plain text keeps every failure visible', () => assert.match(transcriptText(result,{organized:false}),/Olá, Henrique\.\n\[Não transcrito: two.mp3/));
run('organized text includes filenames', () => assert.match(transcriptText(result,{organized:true}),/1. one.mp3/));
run('timestamped text handles absent end time', () => assert.match(transcriptText(result,{timestamps:true}),/\[00:00 – --:--\]/));
run('cancelled result explicitly marked partial', () => assert.match(transcriptText({...result,cancelled:true},{}),/documento parcial/));
run('output filename neutralizes path characters', () => assert.equal(filenameFor('../a:b','pdf'),'..-a-b.pdf'));
run('PDF wrapping splits long words without dropping characters', () => assert.deepEqual(wrapText('abcdef',3,s=>s.length),['abc','def']));
run('Vercel publishes only dist, without Python API', async () => { const config=JSON.parse(await readFile(new URL('../vercel.json',import.meta.url))); assert.equal(config.outputDirectory,'dist'); assert.equal(config.framework,null); assert.equal(config.functions,undefined); });
